require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-capybara

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'config/routes.rb'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 16
  Exclude: 
    - 'db/migrate/**'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Metrics/ClassLength:
  Max: 120
