require:
  - rubocop-rails

inherit_mode:
  merge:
    - Include

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'config/initializers/simple_form_bootstrap.rb'

Rails:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/EnumHash:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - staging
    - production

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/EmptyMethod:
  Enabled: false

Style/StderrPuts:
  Enabled: true
  Exclude:
    - 'bin/**/*'

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Style/RescueStandardError:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
  CountComments: false
  Max: 100

Layout/LineLength:
  Enabled: true
  Max: 160

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/**/*'
    - 'config/initializers/**/*'

Metrics/MethodLength:
  Enabled: false
  CountComments: false
  Max: 10

Metrics/AbcSize:
  Enabled: false
  Max: 15

Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 6

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 15

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/Debugger:
  Enabled: false

Lint/UnreachableCode:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Security/Open:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
