require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
