name: Auto-fix RuboCop

on:
  push:
    branches-ignore: [main]

jobs:
  rubocop-fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Auto-correct RuboCop offenses
        run: bundle exec rubocop -A

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "fix: auto-correct RuboCop offenses"
